### ISSUE TITLE
Add support for rules_oci

### ISSUE THREAD

**Issue by abrisco** [abrisco/rules_helm#12]
Since [rules_docker](https://github.com/bazelbuild/rules_docker) is dead, we should make sure this repo continues to work with the community driven perspective replacement [rules_oci](https://github.com/bazel-contrib/rules_oci).

**Comment by opicaud** [comment]
Hey abrisco,
How do you see the migration, can i help on this part ?

**Comment by abrisco** [comment]
Hi! Given that rules_docker is pretty dead, I wouldn't be opposed to a direct port. But I unfortunately have little experience with rules_I I and would need to figure out what can be done to best maintain existing interfaces. If you have the context I'd be happy to review a pull request!

**Comment by opicaud** [comment]
I would try a non-breaking change to support rules_oci : in case rules_helm is improved, existing « rules_docker » users would got those improvement, without having to migrate everything from to « rules_oci » first. 
This is currently the problem i am facing, being able to smoothly migrate and release from rules_docker to rules_oci with the less impacts on other rules, like helm_rules. What do you think ?

**Comment by abrisco** [comment]
Yeah, that sounds great! I'm not aware of anyone else using the rules so if there are it'd definitely be good to go with a non-breaking change 😀

**Comment by opicaud** [comment]
Hey @abrisco 

Hope you are fine :) 
I continued some experiments, i am currently using `rules_oci` with `rules_helm` without any migration 
It's perfectly fine to push some images with `rules_oci` and then running the chart with some `helm_*` rule.

So I am reopening the discussion because i am currently migrating to Bazel 6. Using `rules_helm` will need definitely a `MODULE.bazel` : but `rules_helm` has a dependency on `rules_docker` which is now deprecated.. 
As I use very rarely the features linked to `rules_docker` I would get it of the deprecated `rules_docker` but keep the related rules just for backward compatibility : basically they would do nothing. This could be a first move if you see the need to implement `rules_oci`

What do you think ?

Olivier

**Comment by opicaud** [comment]
Hey @abrisco 

I started the migration and as you will see [here](https://github.com/opicaud/rules_helm), i've started to add a `oci_images` attribute to support rules_oci.
The issue i am facing is that to use the option `-image_manifest` we need the equivalent of `PushInfo` provided by `rules_docker`. 
I have checked and currently this kind of Info in not available in `rules_oci`. 
I will try to find out an idea, feel free if you have already something in mind.

Olivier

**Comment by opicaud** [comment]
Hey @abrisco 
See [#244](https://github.com/bazel-contrib/rules_oci/pull/244#issuecomment-1575654791) and tell me what you think.
Thanks

Olivier

**Comment by opicaud** [comment]
Hey @abrisco 
I've found that key in values.yaml file were not updated with PushInfo, Is that a bug ? 
This is what i have now after building `with_image_deps`
```
bazel_produced_images:
  image_a:
    url: "docker.io/rules_helm/test/image_a@sha256:42e3409ea3f12966053464d033394bf2900716dcba605908bae54692acc13041"
  image_b:
    url: "docker.io/rules_helm/test/image_b@sha256:42e3409ea3f12966053464d033394bf2900716dcba605908bae54692acc13041"
```
The change is available [here](https://github.com/opicaud/rules_helm/commit/6a396af1eaeca8097922b849fc249ba36fd9c47e). 


I've also pushed an update in helm_install to use  oci_push, but I don't see how we can adapt the helm_package rule to fetch such info for `rules_oci`.. in `rules_docker`, it seems we have the info before pushing, with `rules_oci` you need first to push in order to get the info, as any PushInfo is available and it won't be..

Thanks

Olivier
